dbt_core_databricks_demo:
  outputs:
    dev:
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      schema: default
      threads: 1
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
    prod:
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      schema: default
      threads: 2
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev