dbt_core_databricks_demo:
  outputs:
    dev:
      catalog: cmonasterios
      host: dbc-56f60291-144c.cloud.databricks.com
      http_path: /sql/1.0/warehouses/c4d20a2db40ba654
      schema: default
      threads: 1
      token: TOKEN
      type: databricks
  target: dev
