name: dbt Core CICD validation
run-name: Validate and deploy project

on:
  push:
    branches:
      - main
env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  DATABRICKS_HOST: https://${{ vars.DATABRICKS_HOST }}

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Validate bundle
        run: databricks bundle validate --target prod
        working-directory: dab

      - name: Validate deploy
        run: databricks bundle deploy --target prod
        working-directory: dab



