name: dbt Core CI validation
run-name: Validate dbt project on Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dbt/models/**'
      - 'dbt/macros/**'
      - 'dbt/tests/**'
      - 'dbt/dbt_project.yml'
      - 'dbt/packages.yml'


env:
  DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
#     dbt validations
      - name: Install dbt
        run: |
          pip install dbt-databricks

      - name: Install dbt dependencies
        run: dbt deps
        working-directory: dbt

      - name: Parse dbt project
        run: dbt parse
        working-directory: dbt

      - name: Compile dbt project
        run: dbt compile
        working-directory: dbt

#     Databricks Job Validation
#      - name: Validate Databricks Asset Bundle
#        run: databricks bundle validate
