name: dbt Core CICD validation
run-name: Validate and deploy project

on:
  push:
    branches:
      - dev
      - main
env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  DATABRICKS_HOST: https://${{ vars.DATABRICKS_HOST }}

jobs:
  bundle-validate:
    name: Bundle Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Set credentials and variables
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "BUNDLE_TARGET=prod" >> $GITHUB_ENV
            echo "DATABRICKS_HOST=https://${{ vars.DATABRICKS_HOST_PROD }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_PROD }}" >> $GITHUB_ENV
            echo "WAREHOUSE_ID=${{ vars.WAREHOUSE_ID_PROD }}" >> $GITHUB_ENV
          else
            echo "BUNDLE_TARGET=dev" >> $GITHUB_ENV
            echo "DATABRICKS_HOST=https://${{ vars.DATABRICKS_HOST_DEV }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEV }}" >> $GITHUB_ENV
            echo "WAREHOUSE_ID=${{ vars.WAREHOUSE_ID_DEV }}" >> $GITHUB_ENV
          fi

      - name: Bundle validate
        run: |
          databricks bundle validate --target $BUNDLE_TARGET \
            --var="warehouse_id=$WAREHOUSE_ID" \
            --var="git_url=${{ vars.GIT_URL }}"
        working-directory: dab

  bundle-deploy:
    name: Bundle deploy (prod only)
    runs-on: ubuntu-latest
    needs: bundle-validate
    if: github.ref_name == 'main'    # solo corre en merge a main
    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Set prod credentials
        run: |
          echo "DATABRICKS_HOST=https://${{ vars.DATABRICKS_HOST_PROD }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_PROD }}" >> $GITHUB_ENV  

      - name: Bundle deploy — prod
        run: |
          databricks bundle deploy --target prod \
            --var="warehouse_id=${{ vars.WAREHOUSE_ID_PROD }}" \
            --var="git_url=${{ vars.GIT_URL }}"
        working-directory: dab



